title: THE awesome title
author: TobiO
email: your-email@git.com
description: > # this means to ignore newlines until "baseurl:"
  testing description

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
